### ISSUE TITLE
Keep report highlight in text box if it's relevant arc was clicked 22,3,24

### ISSUE THREAD

**Issue by dankatzman** [4Z1KD/HolyCluster#42] opened 2024-09-22 20:30 UTC
As of now, if you pass with the mouse over an arc, the arc and it's relevant info in the text area is highlighted. 
The moment you move on with the mouse, the text stops being highlighted and you may forgets what it was?. 

I suggest that if you click on an arc, the text will stay highlighted as long as you do not click on the arc again.
if you click on the relevant text in the text area, the highlight will end. 

There is a already a definition what happen if you click on the DX or DE stations or on the frequency.

**Comment by 4Z1KD** [comment] 2024-10-13 18:22
Duplicate of #56

**Closed by 4Z1KD** 2024-10-13 18:22 UTC
